### ISSUE TITLE
I need your help please

### ISSUE THREAD

**Issue by clhoude** [thdoan/magnify#1]
Hello, can you explain to me how to make the plugin works only on a single image? Because the plugin load on all my images from my website. 

Thank you, wishing you a pleasant day. Sorry for my bad English.

**Comment by thdoan** [comment]
Hi, you can add an 'id' attribute to the image tag and only target that id. See this fiddle:

http://jsfiddle.net/10basetom/sbb3trhw/

**Comment by clhoude** [comment]
Thank you very much !
