### ISSUE TITLE
Option to turn it off?

### ISSUE THREAD

**Issue by navar45000** [thdoan/magnify#17]
With multiple images on the page I would like to enable it and disable it for a given image.  Is there a way to disable the magnifier after it's been initialized.  Do you just set the timeout to -1 to turn it off?

Actually tested the timeout to -1 and it doesn't work.  You need like a kill/destroy option.'

Ok, looked at source code and tried $(".magnify").off and seems to work but it doesn't completely remove itself as the checkbox I have positioned over the image hasn't reappeared, as I think it does something to manipulate z index.

**Comment by thdoan** [comment]
This was marked as an enhancement in issue #8 but I forgot all about it. Thanks for the reminder, I'll add this before I forget again.

**Comment by thdoan** [comment]
OK, public method added to destroy the zoom in v1.6.7.
