### ISSUE TITLE
Resize or rotate - how to re-initialize?

### ISSUE THREAD

**Issue by dcasey160** [thdoan/magnify#18]
This works great!  But if I change the size of the window, or rotate (landscape to/from portrait orientation), the cursor and magnifier are offset.
I added a $(window).resize function:
`<script>`
`$(window).resize(function() {`
`  // Initiate magnification powers`
`  $('.zoom').init();`
`  $('.zoom').magnify();`
`});`
`</script>`
which works fairly well, but often on mousemove/touchmove, the magnifier "blinks" as it moves (visible then invisible then visible), and it seems more "jerky" on an iPad when this happens.

**Comment by thdoan** [comment]
Hey thanks for pointing this out -- I'll get this fixed when time permits...

**Comment by thdoan** [comment]
That has been fixed and will be released in v1.6.8.

**Comment by dcasey160** [comment]
Thank you for the fast turnaround!
