### ISSUE TITLE
Not working as expected

### ISSUE THREAD

**Issue by twixchopra** [thdoan/magnify#2]
Hi

First of all very beautiful plugin. I really liked it.

I am integrating this plugin with the [woocommerce](https://github.com/woothemes/woocommerce) so that user can see product with magnify effect.

For that, I have added one more field in to the back end to insert Large Image and then adding `data-magnify-src` to the `<a>`  and it is working perfect.

But issue occurs when Large image is not uploaded.

**ISSUE**

Issue is when Large image is not uploaded at that time,it should take the image SRC of the parent `<a>` as [mentioned](https://github.com/thdoan/magnify#step-2-specify-the-large-image) but if I inspect element, I can see that it is taking the permalink from the URL. What might be the isuse here  ?

![temporary1](https://cloud.githubusercontent.com/assets/10846213/6992453/184573ee-daed-11e4-8ac3-b239dc01a1c9.png)

**Comment by thdoan** [comment]
I can't do anything if the zoom image isn't uploaded, but I will make it handle this error situation more gracefully by disabling the zooming when there is no zoom image. Thanks for bringing this up. Expect a fix soon.

**Comment by twixchopra** [comment]
Thank you so much for your response. Waiting for a new version.

**Comment by thdoan** [comment]
Fixed in commit 5042502749bcb38d60ba2b23bfa83bb0a06e8948. This will be released as part of v1.3.0.
