### ISSUE TITLE
Magnify zoomIn is too big

### ISSUE THREAD

**Issue by Mojo90** [thdoan/magnify#20]
Hi,
I have a problem with Chrome and Firefox. In safari it works just fine.
I have a Magnifier in use and have a img-container with fixed height of 350px. In there is a img with max-width and max-height of 100%. Then I magnify this image. The problem is now for Chrome and Firefox that the magnify class is bigger than my 350px img-container. Than I tried to also give the magnify class a width and height of 100%. But than the Lenses work as the image would still be bigger so it does not really fit.
Can you help here? Not sure how to fix that but I love the lenses :)
Here you can watch in different browsers: https://hyphyweb-development.herokuapp.com/products/31/adidasxyz

**Comment by Mojo90** [comment]
Sorry I added width and height of magnify after I called magnifying. If I add it before it works like a charm :) maybe you should add this to your fork as well? (Or should I make a quick PR?)

**Comment by Mojo90** [comment]
No sorry does not work as expected. Magnify has now max width and height of 100% and outer div has fixed height and img has max width and height of 100% but img has bigger height than magnify.
```
<div class="img-container">
    <span class="helper"></span><i class="fa fa-search fa-2x" aria-hidden="true"></i>
    <div class="magnify">
        <div class="magnify-lens" style="background: transparent url(&quot;http://www.allikestore.com/media/catalog/product/c/o/converse-chuck-taylor-ii-hi-_engineered-canvas_-castlerock-silver-4.jpg&quot;) no-repeat scroll 0px 0px;"></div>
        <img style="display: block;" class="zoomIn" src="http://www.allikestore.com/media/catalog/product/c/o/converse-chuck-taylor-ii-hi-_engineered-canvas_-castlerock-silver-4.jpg" alt="null" onerror="this.src=&quot;/img/dummy-pic.png&quot;;">
    </div>
</div>
```
```
#image_holder .img-container {
    height: 350px;
    text-align: center;
    img {
        vertical-align: middle;
        max-width: 100%;
        max-height: 100%;
    }
    .magnify {
      max-height:100%;
      max-width:100%;
    }
}
```
Not sure how to fix that. Is ugly with chrome and firefox does look as expected in safari. have a look at above link.

**Comment by thdoan** [comment]
@Mojo90 Your demo looks fine in my Chrome (53.0.2785.57 beta-m).

**Comment by Mojo90** [comment]
Yes sorry I fixed that in the last days. Maybe you could adjust Magnifying Class that the img could definetely not be higher than magnifying. (To let you know: I only use original Size of image and not big and small image)
(SCSS-Code)
```
.image_holder .img-container {
    height: 350px;
    text-align: center;
    img {
        max-width: 100%;
        max-height: 350px;
    }
    .magnify {
        max-height: 100%;
        max-width: 100%;
    }
}
```
With this it works like a charm. Because magnify can maximal be at high of image holder and max-height should be set to height of imageHolder than I think it is perfect. And I suggest to add a option for this (Or if you know a more cleaner solution let me know..)
Nevertheless: great Library I do really love it 😊

**Comment by thdoan** [comment]
Hey thanks for reporting this :). I will add some code to prevent this in the future. Do you mind reproducing the issue in a codepen or something so that I can verify my fix? Thanks again!

**Comment by Mojo90** [comment]
I prefer jsfiddle ;) there you go: https://jsfiddle.net/dm3vbxxw/2/ works for me like a charm in safari but in chrome and firefox img has immediately 100% height.

Yes a good point with the sizes, thank you! we already have several image sizes on our agenda cause we are currently building this platform from scratch but will come definetely! :)

**Comment by thdoan** [comment]
@Mojo90 I made a slight change in your CSS to fix this :)

.imageHolder img{
  max-height: 350px;
}

https://jsfiddle.net/thdoan/s9rb86o7/2/

**Comment by Mojo90** [comment]
Yep thx I fixed it exactly like this. But where does this come from? If  the outer div has a height of 350px and the inner img max-height of 100%. it should never ever be bigger or am I wrong?
It is okay for me now but I prefer a solution with percentage because sometimes I have to change those values with Javascript, not a problem but I always prefer pure css if possible :)
But one more time: really great magnifying class I really love it :D!!!

**Comment by thdoan** [comment]
> If the outer div has a height of 350px and the inner img max-height of 100%. it should never ever be bigger or am I wrong?

I think I found the answer to this question: "Some properties in CSS inherit the value of the parent automatically, some don't. Minimum height must be explicitly stated when you want it to inherit the parent's value." ([Source](http://stackoverflow.com/questions/5879668/how-to-enforce-the-height-of-inner-div-to-be-equal-to-the-height-of-the-parent-d))

The Magnify plugin inserts a div immediately below .imageHolder, so the final structure looks like this:

`div.imageHolder > div.magnify > img`

This is an easy fix then -- add the following to `.magnify` and it should fix the issue and you can keep your original CSS:

```
width: inherit;
max-width: inherit
height: inherit;
max-height: inherit
```

**Comment by thdoan** [comment]
> It is okay for me now but I prefer a solution with percentage because sometimes I have to change those values with Javascript, not a problem but I always prefer pure css if possible :)

Just curious, what's the difference between what your goal is (A) and what the alternative is (B)? In both cases you have to specify 350px somewhere; the only difference I can see is that you're specifying it as a value of `max-height`` in instead of `height`. The advantage of (B) is it uses less code.

(A)
```
#image_holder .img-container {
    height: 350px;
    text-align: center;
    img {
        vertical-align: middle;
        max-width: 100%;
        max-height: 100%;
    }
    .magnify {
      max-height:100%;
      max-width:100%;
    }
}
```

(B)
```
#image_holder .img-container {
    text-align: center;
    img {
        vertical-align: middle;
        max-height: 350px;
    }
}
```

**Comment by Mojo90** [comment]
Yes less code and change only one element instead of two. Always better, isn't it?
