### ISSUE TITLE
magnify with owl carousel!

### ISSUE THREAD

**Issue by andreaforapani** [thdoan/magnify#21]
Dear thdoan,

i am using magnify.js on a slider, owl-carousel in shopify.
It works perfectly on the first image, but as soon as i slide to the second image, the lens doesn't appear.

i checked and **.zoom** & **data-magnify-search=""** are there, in all the images.

i attached the code in product page:

<ul class="photos-slider">
      {% for image in product.images %}
        <li class="photos-slider-item" pic-{{forloop.index}}>
          <a class="photo modal-link">
            <img src="{{ image.src | product_img_url: '1024x1024' }}" rel="gallery" alt="{{ image.alt | escape }}" data-image-id="{{ image.id }}" class="zoom" data-magnify-src="{{ image.src | product_img_url: '1024x1024' }}" />
          </a>
        </li>
      {% endfor %}
</ul>

and in theme:

  {% if template == "product" %}
    {{ 'jquery.magnify.js' | asset_url | script_tag }}
    {{ 'jquery.magnify-mobile.js' | asset_url | script_tag }}

    <script>
$(document).ready(function() {
  $('.zoom').magnify({
    speed: 200,
  });
});
</script>

  {% endif %}

Could you help? 
How do i need to reinit the magnifier to work on every image?
I hope this is not something odd, what i am saying.
Thanks for your patience!

Andrea

<img width="1440" alt="screen shot 2016-09-06 at 09 30 47" src="https://cloud.githubusercontent.com/assets/2642158/18265188/aefa0590-7414-11e6-9b2a-40e164414094.png">

**Comment by thdoan** [comment]
Owl Carousel shifts the image positions around to get you the sliding effect, so you'll have to refresh Magnify on every slide change. Here's how to integrate Magnify into Owl Carousel:

http://codepen.io/thdoan/pen/WGvNWb

Make sure you're using Magnify v1.6.10 or higher.

**Comment by andreaforapani** [comment]
Dear thdoan, thanks a lot for your help!

Unfortunately i am using OwlCarousel v1.3.2
it seems there is no "onTranslated", this was just added in Owlcarousel 2, if my understanding is correct.

I use Magnify v1.6.10
Is there another way?

Thanks for your precious help,

Andrea





my code is this: 

$(function() {
  // Initiate carousel
  $('.template--product .photos-slider').owlCarousel({

    touchDrag: false,
    mouseDrag: false,

    autoPlay: false,
    autoPlaySpeed: 1000,
    autoPlayTimeout: 1000,
    autoPlayHoverPause: false,

    margin: 0,
    padding: 0,
    autoHeight: true,

    items: 3,
    // nav: false,
    loop: true,

    navigation: true,
    navigationText: [
      "<i class='glyph--arrow-wide-left'></i>",
      "<i class='glyph--arrow-wide-right'></i>"
    ],

    // Responsive
    responsiveClass: true,
    responsive: {
      0: {
        items: 2,
        // nav: false,
        loop: true
      },
      600: {
        items: 3,
        // nav: false,
        loop: true
      },
      1000: {
        items: 3,
        // nav: false,
        loop: true
      }
    },
    onTranslated: function() {
      // Update Magnify when slide changes
      $zoom.destroy().magnify();
    }
  });
  // Initiate zoom
  var $zoom = $('.zoom').magnify({
    speed: 200,
  });
});

**Comment by thdoan** [comment]
@andreaforapani Here's how to integrate Magnify into Owl Carousel 1.x:

http://codepen.io/thdoan/pen/vXNBjG

This assumes you're using the default pagination speed of 800 ms (see reference below). If you're using a different pagination speed, then change the `setTimeout()` delay parameter accordingly.

Reference: http://owlgraphic.com/owlcarousel/#customizing

**Comment by andreaforapani** [comment]
thdoan. thank you for that!
this is sublime!
thanks for your help.

your magnify is a blessing! ;)

**Comment by thdoan** [comment]
@andreaforapani Cool, glad it worked out for you :).
