### ISSUE TITLE
Angular Data Binding is not working

### ISSUE THREAD

**Issue by KalaiselvanMahendran** [thdoan/magnify#24]
Am trying this magnify in angular web application. this is not working for angular data-binding in large image

this is my code (not working)
```
        <div class="g-spr-feat">
		    <img id="sprFeatImg" src="{{currentImage}}" alt="hob" class="zoom" data-magnify-src="{{currentImage}}">
		</div>
```
If i give direct path in data-magnify-src, Its working

**Comment by thdoan** [comment]
I'm not familiar with Angular apps, but is it possible Magnify is loaded before `{{currentImage}}` is evaluated?

**Comment by KalaiselvanMahendran** [comment]
Checkout this [https://github.com/KalaiselvanMahendran/Angular-Image-Zoom](https://github.com/KalaiselvanMahendran/Angular-Image-Zoom)

**Comment by thdoan** [comment]
It appears to be working for me:

![image](https://cloud.githubusercontent.com/assets/4110567/19464315/cf6f64d4-952d-11e6-935e-6aa868394bb3.png)

**Comment by KalaiselvanMahendran** [comment]
​Yeah it will work, that was developed my me.​



 Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=kalaiselvanmahendran@gmail.com&idSignature=22>

Thanks & Regards,


*Kalaiselvan Mahendran*
*+ 91 9003321521*

**Comment by thdoan** [comment]
Hi, it's just as I suspected: the Angular JS is very large, so it is loaded after Magnify JS. The problem is when Magnify initiates the `{{currentImg}}` token is not yet evaluated to the image URL, so Magnify fails to initiate properly.

To account for this and ensure Magnify is only initiated _after_ Angular, you need to call Magnify after the image is loaded. It's now working for me with this code (be sure to put `magnify.css` and  `jquery.magnify.js` in the same directory first):

```
<!DOCTYPE html>
<html ng-app="Magnify">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Magnify</title>
  <link rel="stylesheet" href="magnify.css">
</head>
<body ng-controller="imageCtrl">

  <img class="product-zoom-small" src="{{currentImg}}" width="200" data-magnify-src="{{currentImg}}">

  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.min.js"></script>
  <script src="http://thecodeplayer.com/uploads/js/jquery-1.7.1.min.js"></script>
  <script type="text/javascript" src="app.js"></script>
  <script type="text/javascript" src="jquery.magnify.js"></script>
  <script>
  $('.product-zoom-small').load(function() {
    $(this).magnify();
  });
  </script>

</body>
</html>
```
