### ISSUE TITLE
imagemap demo question

### ISSUE THREAD

**Issue by dcasey160** [thdoan/magnify#26]
Hello.  On the new image map ability demo, I see I the click being sent to the image map and then we head to say the Google site like we should.  Then if I hit the back button, the lens is in the position where I'd left it (until I place the mouse on the image again) and the page no longer registers clicks unless I refresh the page.  This behavior is on Safari.
On Firefox, the click on the image map actually doesn't seem to register at all.
On Chrome, the click on the image map does send me to the proper links, and after hitting the Back button, the image map still responds to clicks normally.  So in summary:
Chrome - works well including after leaving the page and returning via Back button
Safari - works on first click to new page, but not after returning
Firefox - doesn't register the first click
Thank you.

**Comment by thdoan** [comment]
Hmm, that's strange. What FF version are you using?

**Comment by dcasey160** [comment]
Firefox 48.0.2 on a Mac, OS X 10.11.6 (El Capitan) - thank you.

**Comment by thdoan** [comment]
@dcasey160 Please close if the Safari back issue has been resolved for you because the Firefox issue cannot be fixed (known issue -- see previous comment).

**Comment by dcasey160** [comment]
The Safari back button issue is resolved now.  Thank you.

**Comment by thdoan** [comment]
@dcasey160 This should also be working in Firefox now (upgrade to [v1.6.16](https://github.com/thdoan/magnify/releases/tag/v1.6.16)).
