### ISSUE TITLE
Using on images that move based on div expanding etc issue

### ISSUE THREAD

**Issue by aaronhb** [thdoan/magnify#27]
Great plugin!!!

I am using on an image that is below accordions and it gets pushed down if you open an accordion and then messes up the alignment of the loop or zoom and it is not aligned with the cursor anymore. Any ideas how to fix?

**Comment by thdoan** [comment]
Can you attach or link to a demo so I can test?

**Comment by thdoan** [comment]
[Demo inside an accordion](http://thdoan.github.io/magnify/demo-accordion.html)

**Comment by aaronhb** [comment]
You rock!!!!
