### ISSUE TITLE
Problem when image is not found

### ISSUE THREAD

**Issue by gpetrioli** [thdoan/magnify#29]
When the image is not found the [code that wraps the image in the `<div class="magnify"></div>`](https://github.com/thdoan/magnify/blob/master/dist/js/jquery.magnify.js#L65) is not run (*since that code is executed on the `load` event of the image*).

But on resize the destroy is executed which unwraps the image.
The code uses [`.unwrap('.magnify')`](https://github.com/thdoan/magnify/blob/master/dist/js/jquery.magnify.js#L239), but using a selector is only introduced in jQuery v3.0 (https://api.jquery.com/unwrap/#unwrap-selector)

**Comment by gpetrioli** [comment]
Perhaps a solution would be to use `replaceWith` on the parent element if it is `.magnify`

**Comment by thdoan** [comment]
Thanks, good catch. I don't use v3 myself, which works in most cases since jQuery probably just ignores the selector for v1 and v2, until we encounter the scenario you mentioned.
