### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by TrySound** [thdoan/magnify#3]
Hi! Cool plugin.
Do you use some builder? Or write everything in `dist`?

**Comment by thdoan** [comment]
Hi, thanks! I'm just writing everything in `dist` at the moment. At one point I considered using Grunt, but this is such a small project I didn't bother; also, I was not able to find a way to incorporate [Ajax Minifier](http://ajaxmin.codeplex.com/) into a Grunt build, so if you know of a way I'm all ears :-).

**Comment by TrySound** [comment]
Why you need ajax minifier?
Two days ago was released new minifier based on postcss [cssnano](https://github.com/ben-eb/cssnano/). It's the best minifier at this days. For JS you can use uglify.

I use gulp, caz it's more flexible then grunt. I can make PR with it if you want.

Next question. Did you think about vanillaJS instead of jQuery? Which browsers you want to support?

**Comment by thdoan** [comment]
Thanks for offering to help. You are free to fork this repo to create a vanilla JS version. Actually, that would be quite useful since, as you said, many people don't or prefer not to load a heavy library like jQuery :-).
