### ISSUE TITLE
limit bounds on magnify glass

### ISSUE THREAD

**Issue by mavrick** [thdoan/magnify#34]
Hi there,

Awesome library first up! 

I wanted to ask if it was possible to restrict the 'bounds' of the magnify glass so i wouldn't go past the edge of an image. Example:

![image](https://cloud.githubusercontent.com/assets/357659/26566292/52d7c5ac-4535-11e7-82c4-3a9245641975.png)

Preferred Result:

![image](https://cloud.githubusercontent.com/assets/357659/26566299/66719bc4-4535-11e7-8361-35693be952c3.png)

I wasn't 100% sure if this could be done with the recent update or not.

Cheers

**Comment by thdoan** [comment]
Hi, thanks ^^. Hmm...interesting scenario. Let me put together a test case and see how we can work this in...

**Comment by thdoan** [comment]
The `limitBounds` option has been added to v2.1.0. You can see a demo here:

https://thdoan.github.io/magnify/demo-background.html

Thanks for the suggestion!

**Comment by mavrick** [comment]
Hi, thanks so much! I will get latest and try this out.

Cheers
