### ISSUE TITLE
Initialize on click 

### ISSUE THREAD

**Issue by thmohd** [thdoan/magnify#35]
Great Work, thank you for this library.

I have multiple images where they changes based on thumbnails clicking. The first image is working good since it is the selected by default and magnify() is initialized on window load. However, when you click on new image I try to reinitialize magnify but no luck.

Any help would be appreciated.

Thanks

**Comment by thdoan** [comment]
You need to first `destroy()` it, then `magnify()`. Examples:

https://codepen.io/thdoan/pen/vXNBjG
https://codepen.io/thdoan/pen/WGvNWb
