### ISSUE TITLE
doesn't magnify if svg area overlaps image

### ISSUE THREAD

**Issue by hfeist** [thdoan/magnify#36]
Not really an issue as the code works beautifully.
But I wonder (hope) if there is a way to make the glass aware of an image that sits behind an svg layer

**Comment by thdoan** [comment]
I'm not aware of a solution at the moment :(.

**Comment by thdoan** [comment]
Auto-close...

**Comment by joserick** [comment]
I have a project with the same problem, @hfeist did you manage to solve it in any other way?
