### ISSUE TITLE
limitBounds improvement request

### ISSUE THREAD

**Issue by mavrick** [thdoan/magnify#37]
Hey mate,

Thanks for the ``limitBounds`` feature a few weeks back. It works a treat! What I'm finding now is, trying to view the edge of an image has become this fine balancing act so the magnify glass doesn't hide. Would it be possible to have a flag that can keep the magnify glass in view until the mouse moves off the image completely?

If the magnify glass can stay in view with ``limitBounds`` but not disappear until the mouse leaves the image. I hope that makes sense.

Cheers

**Comment by thdoan** [comment]
That's possible, but it would ruin the zoom experience because you'll be able to see the edges of the image in the lens after you move off of it.
