### ISSUE TITLE
VanillaJS

### ISSUE THREAD

**Issue by TrySound** [thdoan/magnify#4]
I would like to use magnify bower name. Create please new branch for revision my vanillajs version and I'll make PR

**Comment by TrySound** [comment]
And give me access, please

**Comment by TrySound** [comment]
My version
https://github.com/TrySound/magnify/tree/fix-vanillajs

**Comment by thdoan** [comment]
@TrySound Cool, I will add a link to your vanilla JS version.

**Comment by TrySound** [comment]
@thdoan Maybe just merge and bump major version?

**Comment by TrySound** [comment]
@thdoan I can send series of prs which will remove jquery step by step
