### ISSUE TITLE
The mobile zoom is not working in iOS

### ISSUE THREAD

**Issue by Lexot** [thdoan/magnify#41]
Strangely enough in the demo about mobile zoom of magnify on iOS devices is working, but on my website it isn't. And I don't think I did it wrong bc on Android devices the mobile zoom IS working.

I already read about the problem on iOS and the click or the touchstart, but if you know a way to fix this (or to tell me what's the problem) I'll be very grateful

**Comment by simonhutchings** [comment]
Did you have any uck with this. I seem to have the same problem, the window pops up but is not pannable with swiping

**Comment by thdoan** [comment]
Does this work for you? https://thdoan.github.io/magnify/demo.html

I just tried it on an iPhone 6 and for the most part it works the same as Android -- the only difference is you have to tap the image once to show the lens, then you can drag the lens around (whereas on Android you can long-touch and drag the lens without lifting your finger).

I also tried the mobile plugin and it works fine on iPhone 6:

https://thdoan.github.io/magnify/demo-mobile.html

**Comment by thdoan** [comment]
Autoclose after two weeks of inactivity...
