### ISSUE TITLE
The close button on mobile uses touchstart event

### ISSUE THREAD

**Issue by superelement** [thdoan/magnify#43]
I have a problem with the close button on mobile. Because it gets handled by "touchstart" event, when I "touchend" (lift my finger off the screen) it triggers an event for the element beneath the magnified image (in my case the burger menu).
It would be good if the event could be overridden with another event, that way I could use "touchend" or "click" to solve this problem.

**Comment by thdoan** [comment]
Thanks for the suggestion, I will incorporate your changes for the next release.
