### ISSUE TITLE
Can't Zoom Images using HandlebarsJs Templating

### ISSUE THREAD

**Issue by CSumm** [thdoan/magnify#49]
I would like to know if it is possible to zoom on pictures that are being passed to client side using HandlebarsJS template system. I have an image I passed using a product's id and would like for it to zoom when hovered over.  So far I have not been successful and followed the instructions which cover if the images are explicitly .jpg in a folder.

Any guidance would help!

**Comment by thdoan** [comment]
Hi, did you ever figure this out? I don't use HandlebarsJS, so sorry I was not able to provide any guidance.

**Comment by CSumm** [comment]
I figured it out by following tutorials to create one from vanilla
javascript.  Thanks for the response!
