### ISSUE TITLE
Problem with transparent PNG

### ISSUE THREAD

**Issue by Klian** [thdoan/magnify#5]
When I use the plugin with a transparent PNG, I can see the thumbnail in the back... 

How can I hide it ?

**Comment by TrySound** [comment]
You can add `background-color` for `.magnify-lens` But I recommend you to use image without transparency.

**Comment by thdoan** [comment]
There's nothing you can do if the image you're using is transparent. You can use transparent images for the thumbnails, but you must keep the zoom image non-transparent (opaque).
