### ISSUE TITLE
Slick slider overflow hidden cuts the lens in the edge of the active slide.

### ISSUE THREAD

**Issue by D4rkiii** [thdoan/magnify#57]
Hey guys,

i like your plugin and it works so far really great.
But now i tried to use this in a slick slider and having a problem that the lens gets cut at the edge because slick needs to use "overflow: hidden" for the slick-list to hide all other slides which are not active.
It would be great if the plugin could create the elements under the body element to prevent overflow hidden problems.

![lens cutted](https://user-images.githubusercontent.com/17470007/53719599-dac98a80-3e5e-11e9-9ddc-d867b58b1395.png)

What do you think?

best regards

**Comment by thdoan** [comment]
Thanks for reporting this. Unfortunately, making this change will require major changes to the plugin, in which case it would be easier to write a new one from scratch. Hence, I will not be fixing this.
