### ISSUE TITLE
In Mobile devices the finger covers the lens to show complete view

### ISSUE THREAD

**Issue by nchetankumar** [thdoan/magnify#58]
In Mobile devices, while zoom lens active by the long press then the lens will be covered with the finger and it should be aligned to the top position lens but still the zoom area is shown in the lens is the point which is taped in device

**Comment by thdoan** [comment]
There is also an option called `touchBottomOffset` to set the vertical offset of the lens just for this purpose.

Alternatively, I recommend using the mobile plugin:

https://thdoan.github.io/magnify/demo-mobile.html
