### ISSUE TITLE
403 link

### ISSUE THREAD

**Issue by mythnc** [thdoan/magnify#64]
In `README.md`, it is said that

> ..... Magnify is based on this tutorial.

But the tutorial link is Forbidden currently.
http://thecodeplayer.com/walkthrough/magnifying-glass-for-images-using-jquery-and-css3

**Comment by thdoan** [comment]
It's working for me as of now. If you cannot access it, try the cached version:

http://webcache.googleusercontent.com/search?q=cache:crOo8hvWGrcJ:thecodeplayer.com/walkthrough/magnifying-glass-for-images-using-jquery-and-css3+&cd=1&hl=en&ct=clnk&gl=us

**Comment by mythnc** [comment]
No, it can't work.

<img width="1095" alt="螢幕快照 2020-02-15 11 57 39" src="https://user-images.githubusercontent.com/459105/74580719-98a34580-4fea-11ea-8268-cc75a23de1db.png">

**Comment by thdoan** [comment]
Your region may be blocked from accessing this site, which would be out of
my control.
