### ISSUE TITLE
How to disable/destroy the magnifier?

### ISSUE THREAD

**Issue by arnoldbird** [thdoan/magnify#8]
I want to create a UI for toggling the magnify functionality off and on.  Turning it on is easy enough, since that's what the magnify function does.  What's the best way to turn it off?

Thanks!

**Comment by polyn0m** [comment]
@arnoldbird try to $('img').unwrap()

**Comment by thdoan** [comment]
I will add a destroy() public method when time permits, but in the meantime you can do as @arnoldbird suggests. Thanks for the input.
