### ISSUE TITLE
Not works in flexbox

### ISSUE THREAD

**Issue by vaso123** [thdoan/magnify#9]
Hi!

I installed your script as you described. I am using flexbox for my products.
When I hover the image, nothing happens. But when I click on my login button, and a popup appeared, and move the mouse at the right side of the image, then magnifier starts to work but at bad position of the page.

I am using jQuery Mobile for my site, this is why I mentioned the popup thing.

**Comment by thdoan** [comment]
Thanks for reporting the issue. Can you put a sample on jsfiddle or codepen? I'll take a look at it.

**Comment by vaso123** [comment]
Hi!

Sorry, this is not an issue. That was myfault. I've added the image, and there was a little image to in the imagelist, with the same class. And the magnify-lens div was attached to this little image, and not to the big image, so it was my fault, your script is working great.
